### PR TITLE
Sg/2024 06 17

### PR DESCRIPTION
**Pull request by docuracy**

### CODE REVIEW

**Comment by docuracy** [comment]
Hang on....

**Comment by docuracy** [comment]
... actually, should be OK as is. Proceed at your leisure!

**Comment by kgeographer** [comment]
merged, but deploy delayed until evening - the `--build` takes a few minutes and now with actual users, want to impact as few as possible. maybe become a nightly routine before lights out

**Comment by kgeographer** [comment]
collection 172 still fails to load - pointing to line 285 this time

**Pull request merged**
