### PR TITLE
Sg/2024 05 24

### PR DESCRIPTION
**Pull request by docuracy**

### CODE REVIEW

**Comment by docuracy** [comment]
Includes inadvertent (but harmless) push of advance work on Issue #210:  server-side validation & emailing operation of contact modal needs testing.

**Comment by kgeographer** [comment]
- top menu not live any more (the new modal and z-index)
- new home page extend below window (extremely in firefox) [1]


[1]
image

**Comment by kgeographer** [comment]
what deleted line would that be? :^)
full screen looks great, but requiring or expecting full screen doesn't seem right to me. I never go full screen and I expose a toolbar, a perfectly normal thing to do. where is the css for the container?

**Comment by docuracy** [comment]
Not full screen, simply maximised rather than resized to occupy only part of the screen.

css is in whg-modal.css

**Comment by docuracy** [comment]
Here it is at the three most common screen resolutions (about 50% of all desktops):

image

image

image

Not so good at 1280x720 (6.58% of desktops) - I wonder if this is what you have?

image

**Pull request merged**
