### PR TITLE
Sg/2023 12 13

### PR DESCRIPTION
**Pull request by docuracy**

### CODE REVIEW

**Comment by docuracy** [comment]
There isn't any performance issue with the page on my system prior to adding any new datasets - it's comparable to the Home and Search pages. For each dataset the initial load brings in only some very light JSON, which includes a geometry URL which is hit only if the user hovers over its card. The main bandwidth on the initial load is probably consumed by the country_feature_collection embedded in the page - in total the page load is 2.4MB: it would make _a lot_ of sense instead to hot-load geometries for individual countries if and when they are selected in the filter.

I noticed the absence of displayed geometries for some of the collections and assumed that there was something quirky about them - the geometry URL is delivering nothing in those cases.

**Comment by kgeographer** [comment]
I have to understand why it takes a minute to load on my system. The geometry on hover is very nice, but has to be performant for the largest datasets and collections, or an automatic alternative for those past a certain size must be arranged. Users will not forgive waiting for anything more than a few seconds. I will merge this, then push it out to dev and ask for the team to report back their experience. We have a last of year mtg on Thursday.

**Comment by docuracy** [comment]
Sure, yes. Now that we have the various mapping options configured (raw | hull | clustered-hull | heatmap) we can more easily assess the performance costs of (a) generating the required GeoJSON on-the-fly, (b) transferring such data over the internet, and (b) rendering on the map.

We discussed at one point the possible desirability of extending the Dataset and Collection models to store in the database a representational geometry for each dataset and collection, but it could be that in some cases simply storing the default render option would suffice. Maybe that's it: an additional string property which would be any of 

1. a word ("raw" | "heatmap")
2. JSONb multipolygon
3. a predefined Area (multipolygon) that can be retrieved via a stored API link

**Comment by docuracy** [comment]
I've moved today's commits into a new branch, so as the previous commits have already been merged into `staging` this PR can now be closed without further merging.

**Comment by kgeographer** [comment]
closing per request -- commits in new branch

**Pull request closed without merging**
