### PR TITLE
Sg/2024 07 14

### PR DESCRIPTION
**Pull request by docuracy**
- [ ] Replace the sample datasets [here](https://github.com/WorldHistoricalGazetteer/whgazetteer/raw/main/example_data/whg_example-data.zip) with valid versions and test them on this revised form before considering moving this branch to staging.

### CODE REVIEW

**Comment by kgeographer** [comment]
hotfixed whg_example-data.zip [07:20, 20 Jul]

**Comment by docuracy** [comment]
Thanks, but following testing I need to adjust the examples because if a delimited dataset includes _any_ features with aat_types, validation requires _all_ to have aat_types even if they have fclasses. Also not sure I've got the UTF-8 encoding right for .jsonld - validation fails but I haven't yet figured out if it's the file or the validation at fault.

**Comment by kgeographer** [comment]
> Thanks, but following testing I need to adjust the examples because if a delimited dataset includes _any_ features with aat_types, validation requires _all_ to have aat_types even if they have fclasses. Also not sure I've got the UTF-8 encoding right for .jsonld - validation fails but I haven't yet figured out if it's the file or the validation at fault.

Over the years, I have attempted several things to validate for utf-8, with mixed success (it works till some file fails). The latest being for delimited files, attempting to read it into a pandas dataframe. Not sure there is any similar for lpf

**Comment by docuracy** [comment]
I'm going to go with allowing UTF _or_ ASCII, I think - but ruling out ANSI. Not sure if the database is configured to handle UTF-16, is it?

**Comment by kgeographer** [comment]
> I'm going to go with allowing UTF _or_ ASCII, I think - but ruling out ANSI. Not sure if the database is configured to handle UTF-16, is it?

The database is UTF8. Postgres does not support UTF-16 directly.

I think allowing ASCII is a mistake. The world is full of non-ASCIII characters, and people struggle sometimes with this, in large part due to Excel's save-as functions sometimes boogering UTF.

**Comment by docuracy** [comment]
OK, ASCII is only there because there's often no way of telling the difference between it and UTF. I'll restrict UTF to UTF-8.

I guess the lack of Postgres UTF-16 support hasn't been an issue.

**Comment by kgeographer** [comment]
> OK, ASCII is only there because there's often no way of telling the difference between it and UTF. I'll restrict UTF to UTF-8.
> 
In mind-bendingly fashion, some ways of detecting encoding decide that if a file has no non-asciii characters then it can't be utf, even if it is

> I guess the lack of Postgres UTF-16 support hasn't been an issue.
It has not been an issue

**Pull request closed without merging**
